export const REQUEST_TABLELIST = 'REQUEST_TABLELIST';
export const RECEIVE_TABLELIST = 'RECEIVE_TABLELIST';
export const ERROR_TABLELIST = 'ERROR_TABLELIST';
export const TOGGLE_TABLE = 'TOGGLE_TABLE';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';